# Generated by Django 5.0.3 on 2024-04-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainatehdas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_avail',
            field=models.CharField(choices=[('Va', 'Vapaa'), ('Vr', 'Varattu'), ('Hu', 'Huollossa'), ('Ri', 'Rikki')], max_length=2, verbose_name='Availability'),
        ),
    ]
