# Generated by Django 5.0.3 on 2024-04-17 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lainatehdas', '0003_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_avail',
        ),
    ]
