# Generated by Django 5.0.3 on 2024-04-17 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainatehdas', '0006_alter_reservation_date_reserved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_avail',
            field=models.CharField(choices=[('Va', 'Vapaa'), ('Vr', 'Varattu'), ('Hu', 'Huollossa'), ('Ri', 'Rikki')], default='vapaa', max_length=2),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_returned',
            field=models.DateField(default=datetime.date(2024, 5, 1)),
        ),
    ]
