# Generated by Django 5.0.3 on 2024-04-17 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lainatehdas', '0007_item_item_avail_alter_reservation_date_returned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='user_id',
            new_name='user',
        ),
    ]
