# Generated by Django 5.0.3 on 2024-04-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainatehdas', '0008_rename_item_id_reservation_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
