# Generated by Django 5.0.3 on 2024-04-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainatehdas', '0014_alter_item_item_avail'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_complete',
            field=models.BooleanField(default=False, verbose_name='Varaus valmis'),
        ),
    ]
