# Generated by Django 5.0.3 on 2024-04-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lainatehdas', '0015_reservation_reservation_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_complete',
        ),
    ]
