# Generated by Django 5.0.3 on 2024-04-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lainatehdas', '0016_remove_reservation_reservation_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_avail',
        ),
    ]
