# Generated by Django 5.0.3 on 2024-04-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainatehdas', '0017_remove_item_item_avail'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_avail',
            field=models.CharField(choices=[('Va', 'Vapaa'), ('Vr', 'Varattu'), ('Hu', 'Huollossa'), ('Ri', 'Rikki')], default='Va', max_length=2),
        ),
    ]
