# Generated by Django 5.0.3 on 2024-04-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lainatehdas', '0018_item_item_avail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_avail',
        ),
    ]
