# Generated by Django 5.0.3 on 2024-04-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainatehdas', '0020_item_item_avail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_reserved',
            field=models.DateField(),
        ),
    ]
