# Generated by Django 5.0.3 on 2024-04-23 14:51

import lainatehdas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainatehdas', '0022_alter_item_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.ImageField(default='images/placeholder.jpg', upload_to='images/', validators=[lainatehdas.models.validate_image_dimensions]),
        ),
    ]
