# Generated by Django 5.0.3 on 2024-04-23 15:12

import lainatehdas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainatehdas', '0023_alter_item_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.ImageField(default='images/placeholder.jpg', upload_to='MEDIA_URL', validators=[lainatehdas.models.validate_image_dimensions]),
        ),
    ]
