# Generated by Django 5.0.3 on 2024-04-23 15:34

import lainatehdas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainatehdas', '0024_alter_item_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.ImageField(upload_to='', validators=[lainatehdas.models.validate_image_dimensions]),
        ),
    ]
