# Generated by Django 5.0.3 on 2024-04-24 07:44

import lainatehdas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainatehdas', '0026_alter_item_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_deadline',
            field=models.DateField(auto_created=lainatehdas.models.Reservation.CalculateDeadline, default=None),
        ),
    ]
