# Generated by Django 5.0.3 on 2024-04-24 07:45

import datetime
import lainatehdas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainatehdas', '0027_reservation_date_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_deadline',
            field=models.DateField(auto_created=lainatehdas.models.Reservation.CalculateDeadline, default=datetime.date(2024, 4, 24)),
        ),
    ]
