# Generated by Django 5.0.3 on 2024-04-24 07:46

import datetime
import lainatehdas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainatehdas', '0028_alter_reservation_date_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_deadline',
            field=models.DateField(auto_created=lainatehdas.models.Reservation.CalculateDeadline, default=datetime.datetime(2024, 4, 24, 7, 46, 32, 772704, tzinfo=datetime.timezone.utc)),
        ),
    ]
