# Generated by Django 5.0.3 on 2024-04-24 07:49

import lainatehdas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainatehdas', '0030_alter_reservation_date_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_deadline',
            field=models.DateField(verbose_name=lainatehdas.models.Reservation.CalculateDeadline),
        ),
    ]
